---
- name: Config_trust_local_keys | List all keys trust levels.
  ansible.builtin.command:
    cmd: gpg2 --export-ownertrust
  register: _gpg2_export_ownertrust
  changed_when: _gpg2_export_ownertrust.rc == 0
  failed_when: _gpg2_export_ownertrust.rc != 0
  run_once: true

- name: Config_trust_local_keys | Set trust level key.
  ansible.builtin.shell:
    cmd: >-
      set -o pipefail && echo -e \"{{ local_key.trust_level }}\ny\n\"
      | gpg2 --batch --command-fd 0 --expert --edit-key {{ local_key.id }} trust
  args:
    executable: /bin/bash
  register: __trust_keys
  changed_when: __trust_keys.rc == 0
  when:
    - local_key.trust_level is defined
    - local_key.trust_level
    - local_key.id + ':' + (local_key.trust_level|int + 1) | string + ':' not in _gpg2_export_ownertrust.stdout
