---
- name: Converge
  hosts: all
  tasks:

    - name: "Converge | Include variable file."
      ansible.builtin.include_vars: variables.yml

    - name: "Converge | Include spreadcat.gnupg2."
      ansible.builtin.include_role:
        name: "spreadcat.gnupg2"
